"""
Phenotype definitions sourced from the OHDSI PhenotypeLibrary.

Phenotypes are loaded from data/phenotype_library.json, which is generated by:
    uv run python scripts/fetch_phenotype_library.py

Each Phenotype has:
    cohort_id   - the OHDSI PhenotypeLibrary cohort ID
    name        - human-readable phenotype name
    concept_ids - list of OMOP standard concept IDs for the primary event criteria
"""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass
from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

_raw_library_path = os.getenv("PHENOTYPES_JSON_PATH", "data/phenotype_library.json")
_library_candidate = Path(_raw_library_path)
if not _library_candidate.is_absolute():
    _library_candidate = Path.cwd() / _library_candidate
_LIBRARY_FILE = (
    _library_candidate
    if _library_candidate.exists()
    else Path.cwd() / "data" / "phenotype_library.json"
)

_CLASSIFICATION_FILE = Path.cwd() / "data" / "phenotypes_classification.csv"


def _load_classification_map(path: Path = _CLASSIFICATION_FILE) -> dict[int, str]:
    """Load cohort_id → system mapping from the manual classification CSV."""
    if not path.exists():
        return {}
    mapping: dict[int, str] = {}
    with path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            try:
                mapping[int(row["Cohort ID"])] = row["Clinical System Classification"].strip()
            except (KeyError, ValueError):
                continue
    return mapping


_CLASSIFICATION_MAP: dict[int, str] = _load_classification_map()


@dataclass(frozen=True)
class Phenotype:
    cohort_id: int
    name: str
    concept_ids: tuple[int, ...]
    system: str = "Other"

    def __post_init__(self) -> None:
        if not isinstance(self.concept_ids, tuple):
            object.__setattr__(self, "concept_ids", tuple(self.concept_ids))


def load_phenotypes(path: Path = _LIBRARY_FILE) -> list[Phenotype]:
    """Load phenotypes from the PhenotypeLibrary JSON file."""
    if not path.exists():
        raise FileNotFoundError(
            f"Phenotype library file not found: {path}\n"
            "Run:  uv run python scripts/fetch_phenotype_library.py"
        )
    raw: list[dict] = json.loads(path.read_text())
    return [
        Phenotype(
            cohort_id=entry["cohort_id"],
            name=entry["name"],
            concept_ids=tuple(entry["concept_ids"]),
            system=_CLASSIFICATION_MAP.get(entry["cohort_id"], "Other"),
        )
        for entry in raw
        if entry.get("concept_ids")  # skip phenotypes with no concept IDs
    ]


PHENOTYPES: list[Phenotype] = load_phenotypes() if _LIBRARY_FILE.exists() else []
